<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220414132507 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs

    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE base CHANGE civ civ VARCHAR(30) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, CHANGE nom nom VARCHAR(150) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, CHANGE prenom prenom VARCHAR(150) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, CHANGE adr1 adr1 VARCHAR(38) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, CHANGE adr2 adr2 VARCHAR(38) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, CHANGE adr3 adr3 VARCHAR(38) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, CHANGE adr4 adr4 VARCHAR(38) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, CHANGE cp cp VARCHAR(10) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, CHANGE ville ville VARCHAR(32) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, CHANGE pays pays VARCHAR(10) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, CHANGE insee insee VARCHAR(5) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, CHANGE iris iris VARCHAR(4) CHARACTER SET latin1 DEFAULT \'000\' NOT NULL COLLATE `latin1_swedish_ci`, CHANGE inseeIris inseeIris VARCHAR(9) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, CHANGE irisCanton irisCanton VARCHAR(2) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, CHANGE sexe sexe CHAR(1) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, CHANGE pro pro VARCHAR(5) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, CHANGE opposeMD opposeMD VARCHAR(3) CHARACTER SET latin1 DEFAULT \'Non\' NOT NULL COLLATE `latin1_swedish_ci`, CHANGE matchmi matchmi VARCHAR(100) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, CHANGE hexacle hexacle VARCHAR(50) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, CHANGE DATEMODIF DATEMODIF VARCHAR(10) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, CHANGE TYPEMODIF TYPEMODIF CHAR(1) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, CHANGE ORIGINE ORIGINE VARCHAR(50) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, CHANGE F_NGROUP F_NGROUP VARCHAR(50) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, CHANGE I_NGroup I_NGroup VARCHAR(50) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, CHANGE F_DUP F_DUP VARCHAR(10) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, CHANGE I_DUP I_DUP VARCHAR(5) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`');
        $this->addSql('ALTER TABLE F_Complement CHANGE F_NGroup F_NGroup VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE postal_origine postal_origine VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE Fix_valeur Fix_valeur VARCHAR(32) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE fix_origine fix_origine VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE fix_id fix_id VARCHAR(20) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE Fix2_valeur Fix2_valeur VARCHAR(32) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE fix2_origine fix2_origine VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE fix2_id fix2_id VARCHAR(20) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE portable_valeur portable_valeur VARCHAR(32) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE portable_origine portable_origine VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE portable_id portable_id VARCHAR(20) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE email_valeur email_valeur VARCHAR(32) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE email_origine email_origine VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE email_id email_id VARCHAR(20) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE statut_habitation_val statut_habitation_val VARCHAR(1) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE statut_habitation_origine statut_habitation_origine VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE statut_habitation_id statut_habitation_id VARCHAR(20) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE type_habitat_val type_habitat_val VARCHAR(1) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE type_habitat_origine type_habitat_origine VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE type_habitat_id type_habitat_id VARCHAR(20) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE csp_val csp_val VARCHAR(1) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE csp_origine csp_origine VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE csp_id csp_id VARCHAR(20) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`');
        $this->addSql('ALTER TABLE I_Complement CHANGE I_NGroup I_NGroup VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE postal_origine postal_origine VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE dnaiss dnaiss VARCHAR(12) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE Fix_valeur Fix_valeur VARCHAR(32) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE fix_origine fix_origine VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE fix_id fix_id VARCHAR(20) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE Fix2_valeur Fix2_valeur VARCHAR(32) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE fix2_origine fix2_origine VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE fix2_id fix2_id VARCHAR(20) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE portable_valeur portable_valeur VARCHAR(32) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE portable_origine portable_origine VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE portable_id portable_id VARCHAR(20) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE email_valeur email_valeur VARCHAR(32) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE email_origine email_origine VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE email_id email_id VARCHAR(20) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE statut_habitation_val statut_habitation_val VARCHAR(1) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE statut_habitation_origine statut_habitation_origine VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE statut_habitation_id statut_habitation_id VARCHAR(20) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE type_habitat_val type_habitat_val VARCHAR(1) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE type_habitat_origine type_habitat_origine VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE type_habitat_id type_habitat_id VARCHAR(20) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE csp_val csp_val VARCHAR(1) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE csp_origine csp_origine VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE csp_id csp_id VARCHAR(20) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`');
    }
}
